from fastapi import APIRouter, Depends, Request
from slowapi import Limiter
from slowapi.util import get_remote_address
from ..schemas.ai import TutorIn
from ..config import settings

limiter = Limiter(key_func=get_remote_address)
router = APIRouter(prefix="/api/ai", tags=["ai"])

@router.post("/tutor")
@limiter.limit("20/minute")
def tutor(request: Request, payload: TutorIn):
    q = payload.question.lower()
    # try real Gemini if key present
    if settings.GEMINI_API_KEY:
        try:
            from ..services.ai.gemini_client import call_gemini
            ans = call_gemini(payload.question, payload.subject)
            return {"answer": ans, "subject": payload.subject, "source": "gemini", "hint": "Generated by Gemini"}
        except Exception as e:
            pass
    # fallback mock
    explanations = {
        "syllogism": "Syllogism shortcut: Use Venn diagrams. All A are B, No B is C => No A is C. Draw two circles!",
        "simplification": "For 48% of 250, do 50% -2% =125-5=120. Faster than calculator.",
        "speed": "Speed = distance/time. 150/15=10 m/s *3.6=36 km/h. Remember 1 m/s =3.6 km/h.",
    }
    for k, v in explanations.items():
        if k in q:
            return {"answer": v, "subject": payload.subject, "source": "mock-gemini", "hint": "Try similar: 36% of 450?"}
    return {"answer": f"Great question: '{payload.question}'. Approach: 1) Identify pattern 2) Eliminate outliers 3) Verify via options. (Set GEMINI_API_KEY for live Gemini)", "subject": payload.subject, "source": "mock-gemini", "hint": "Practice 10 similar Qs via /ai/generate-questions"}

@router.post("/generate-questions")
def generate(topic: str = "Quants", count: int = 3):
    from sqlalchemy.orm import Session
    from fastapi import Depends
    from ..database import get_db
    # dummy - real impl uses question_generator service
    return {"topic": topic, "note": "Wire app/services/ai/question_generator.py for Gemini generation"}

@router.get("/weakness-analysis")
def weakness(user: str = "demo@bankprepare.ai"):
    return {"user": user, "weak_topics": ["Data Interpretation (52%)", "Error Spotting (48%)", "Blood Relations (60%)"], "recommendation": "Focus 30 mins daily on DI.", "generated_quiz_id": 2}
