QUESTIONS = [
    # Quants
    {"subject": "Quants", "topic": "Simplification", "difficulty": "easy", "text": "What is 48% of 250?", "options": ["110", "120", "130", "100"], "answer_idx": 1, "explanation": "48% = 48/100. 48/100*250 = 120."},
    {"subject": "Quants", "topic": "Speed & Distance", "difficulty": "medium", "text": "A train 150m long crosses a pole in 15 seconds. What is its speed in km/h?", "options": ["28 km/h", "36 km/h", "40 km/h", "32 km/h"], "answer_idx": 1, "explanation": "150/15=10 m/s *3.6=36 km/h"},
    {"subject": "Quants", "topic": "Data Interpretation", "difficulty": "hard", "text": "If ratio of A:B is 3:4 and B:C is 2:5, what is A:C?", "options": ["3:10", "3:5", "6:20", "3:8"], "answer_idx": 0, "explanation": "A:B=3:4=6:8, B:C=2:5=8:20 => A:C=6:20=3:10"},
    {"subject": "Quants", "topic": "Arithmetic", "difficulty": "medium", "text": "A shopkeeper marks 40% above cost and gives 10% discount. Profit %?", "options": ["26%", "28%", "30%", "22%"], "answer_idx": 0, "explanation": "100 -> 140 -> 126 => 26% profit."},
    {"subject": "Quants", "topic": "Number Series", "difficulty": "medium", "text": "Find next: 2, 6, 12, 20, 30, ?", "options": ["40", "42", "44", "36"], "answer_idx": 1, "explanation": "n(n+1): 1*2,2*3,3*4,4*5,5*6,6*7=42."},
    # Reasoning
    {"subject": "Reasoning", "topic": "Puzzles", "difficulty": "medium", "text": "If A is brother of B, B is sister of C, how is A related to C?", "options": ["Brother", "Sister", "Cousin", "Cannot determine"], "answer_idx": 0, "explanation": "A brother of B & B sister of C => A is brother of C."},
    {"subject": "Reasoning", "topic": "Syllogism", "difficulty": "medium", "text": "All pens are pencils. All pencils are erasers. Conclusion: All pens are erasers.", "options": ["True", "False", "Cannot be determined", "Only 1 follows"], "answer_idx": 0, "explanation": "Transitive: pens -> pencils -> erasers, so True."},
    {"subject": "Reasoning", "topic": "Blood Relation", "difficulty": "easy", "text": "X is son of Y. Y is daughter of Z. How is X related to Z?", "options": ["Grandson", "Son", "Nephew", "Cousin"], "answer_idx": 0, "explanation": "Y daughter of Z, X son of Y => X grandson of Z."},
    # English - FIXED: proper English questions only
    {"subject": "English", "topic": "Error Spotting", "difficulty": "easy", "text": "Find error: 'Each of the boys have finished their homework.'", "options": ["Each", "have", "finished", "No error"], "answer_idx": 1, "explanation": "'Each' is singular -> 'has' not 'have'."},
    {"subject": "English", "topic": "Cloze Test", "difficulty": "medium", "text": "The report ___ that inflation will ease by Q4.", "options": ["indicate", "indicates", "indicated", "indicating"], "answer_idx": 1, "explanation": "Singular subject 'report' -> 'indicates'."},
    {"subject": "English", "topic": "Reading Comprehension", "difficulty": "medium", "text": "Synonym of 'Abundant' as used in banking context?", "options": ["Scarce", "Plentiful", "Meagre", "Limited"], "answer_idx": 1, "explanation": "'Abundant' = plentiful / ample."},
    {"subject": "English", "topic": "Fill in the Blank", "difficulty": "easy", "text": "He has been working here ___ 2020.", "options": ["since", "for", "from", "by"], "answer_idx": 0, "explanation": "'since' for point of time, 'for' for duration."},
    {"subject": "English", "topic": "Para Jumble", "difficulty": "hard", "text": "S1: RBI controls inflation. S2-? P: Repo rate is raised. Q: Credit becomes costly. R: Demand falls. S: Prices stabilise.", "options": ["PQRS", "PRQS", "QPRS", "PQSR"], "answer_idx": 0, "explanation": "Logical flow: raise repo -> costly credit -> demand falls -> prices stabilise = PQRS."},
    {"subject": "English", "topic": "Vocabulary", "difficulty": "easy", "text": "Antonym of 'Prudent' (often used for bankers):", "options": ["Careful", "Reckless", "Wise", "Cautious"], "answer_idx": 1, "explanation": "'Prudent' = careful/wise, antonym = reckless."},
    {"subject": "English", "topic": "Error Spotting", "difficulty": "medium", "text": "Find error: 'The committee have submitted its report.'", "options": ["The committee", "have", "its", "No error"], "answer_idx": 1, "explanation": "'Committee' collective singular -> 'has'."},
]
